### ISSUE TITLE
Offcanvas closing when interacting with dropdown

### ISSUE THREAD

**Issue by MikiSoft** [jasny/bootstrap#457]
Title says it all. I have this issue on Firefox (using PC) and I've heard someone here [talking about the same happening on Android browser](https://github.com/jasny/bootstrap/issues/412) (probably stock since he didn't mentioned which exactly). Not sure about other browsers, people should report here where also that bug is present.

**Comment by kosiakMD** [comment]
Have this problem in mobile browsers. It,s work only after open the dropdown menu than close and open again offcanvas menu, dropdown is still open and will work submenu.
May be problem is in propagation...

**Comment by jasny** [comment]
This should be fixed with PR #405. Please try the beta.

**Comment by MikiSoft** [comment]
@jasny: https://raw.githubusercontent.com/jasny/bootstrap/master/dist/js/jasny-bootstrap.min.js - you mean this? I've tested it now and it doesn't work. Also where's beta release?

**Comment by MikiSoft** [comment]
@jasny: I've tested it right now with the beta release and it still doesn't work, so I've reopened the issue (which is linked above).

**Comment by Minstel** [comment]
@MikiSoft @jasny 
Well, the reason for this seems pretty simple. If we take a look at bootstrap code, that handles opening dropdown, we'll find the following:

```
Dropdown.prototype.toggle = function (e) {
  ...
  if ('ontouchstart' in document.documentElement && !$parent.closest('.navbar-nav').length) {
    ...
    ... .addClass('dropdown-backdrop')
    ...
  }
}
```

So we can see, that backdrop is added in any case, when:
- device is touchable
- and dropdown does not have `.navbar-nav` among it's parent. Like if it is intended to be used only in that way.

Unfortunately, first condition can become `true` in FF. See this issue: https://github.com/twbs/bootstrap/issues/13748. Also it points to coresponding FF bug. According to this, users, that do not use dev tools, will never face that behaviour. That's good)

The way to solve this for us, developers, seems the following: to add `navbar-nav` class to one of dropdown parents (for ex., to offcanvas menu). And if we do not need it's style effects, then compensate them with other styles.

Maybe it's not the way this class should be used, but it can solve the problem.
